import { Poll, RecentPoll } from './types';

export const mockPolls: Poll[] = [
  {
    id: 'poll-1',
    internalName: 'Penalty Call Q1',
    question: 'Was that a penalty?',
    slug: 'penalty-call',
    state: 'live',
    options: [
      { id: 'opt-1a', text: 'Yes', shortLabel: 'YES', votes: 4827, order: 0 },
      { id: 'opt-1b', text: 'No', shortLabel: 'NO', votes: 3156, order: 1 },
    ],
    totalVotes: 7983,
    votesPerSecond: 12,
    template: 'horizontal-bar',
    themeId: 'broadcast-clean',
    showLiveResults: true,
    hideUntilClose: false,
    minVoteThreshold: 100,
    allowVoteChange: false,
    autoCloseDuration: 120,
    showThankYou: true,
    showFinalResults: true,
    createdAt: '2025-01-15T19:00:00Z',
    openedAt: '2025-01-15T19:32:00Z',
  },
  {
    id: 'poll-2',
    internalName: 'Game Winner',
    question: 'Who wins tonight?',
    slug: 'game-winner',
    state: 'ready',
    options: [
      { id: 'opt-2a', text: 'Rangers', shortLabel: 'NYR', votes: 0, order: 0 },
      { id: 'opt-2b', text: 'Devils', shortLabel: 'NJD', votes: 0, order: 1 },
    ],
    totalVotes: 0,
    votesPerSecond: 0,
    template: 'pie-donut',
    themeId: 'dark-ice',
    showLiveResults: true,
    hideUntilClose: false,
    minVoteThreshold: 50,
    allowVoteChange: false,
    showThankYou: true,
    showFinalResults: true,
    createdAt: '2025-01-15T18:00:00Z',
  },
  {
    id: 'poll-3',
    internalName: 'Key Factor',
    question: 'What matters more tonight?',
    slug: 'key-factor',
    state: 'closed',
    options: [
      { id: 'opt-3a', text: 'Goaltending', shortLabel: 'GTD', votes: 2891, order: 0 },
      { id: 'opt-3b', text: 'Special Teams', shortLabel: 'SPT', votes: 1842, order: 1 },
      { id: 'opt-3c', text: 'Forecheck', shortLabel: 'FCK', votes: 1567, order: 2 },
    ],
    totalVotes: 6300,
    votesPerSecond: 0,
    template: 'vertical-bar',
    themeId: 'silver-neutral',
    showLiveResults: true,
    hideUntilClose: false,
    minVoteThreshold: 100,
    allowVoteChange: false,
    showThankYou: true,
    showFinalResults: true,
    createdAt: '2025-01-14T20:00:00Z',
    openedAt: '2025-01-14T20:15:00Z',
    closedAt: '2025-01-14T20:45:00Z',
  },
];

export const recentPolls: RecentPoll[] = [
  { id: 'poll-1', name: 'Penalty Call Q1', date: '2025-01-15', template: 'horizontal-bar', totalVotes: 7983, state: 'live' },
  { id: 'poll-3', name: 'Key Factor', date: '2025-01-14', template: 'vertical-bar', totalVotes: 6300, state: 'closed' },
  { id: 'poll-2', name: 'Game Winner', date: '2025-01-15', template: 'pie-donut', totalVotes: 0, state: 'ready' },
  { id: 'rp-4', name: 'Best Goal Celebration', date: '2025-01-13', template: 'pie-donut', totalVotes: 12450, state: 'archived' },
  { id: 'rp-5', name: 'MVP of the Period', date: '2025-01-12', template: 'horizontal-bar', totalVotes: 8920, state: 'archived' },
];

export const templateLabels: Record<string, string> = {
  'horizontal-bar': 'Horizontal Bar',
  'vertical-bar': 'Vertical Bar',
  'pie-donut': 'Pie / Donut',
  'progress-bar': 'Progress Bar',
  'puck-slider': 'Puck Slider',
  'fullscreen-hero': 'Fullscreen Hero',
  'lower-third': 'Lower Third',
};
